from typing import Any, Literal

from pydantic import BaseModel, Field


DraftType = Literal["summary", "reply", "user_story"]


class TicketSummary(BaseModel):
    """Represent structured ticket summary generated by AI.

    Parameters:
        title: Short summary title.
        problem: Customer problem statement.
        impact: Business or user impact.
        suggested_next_steps: Recommended actions.
        risks: Known risks or missing data.

    Returns:
        Validated summary content.

    Edge cases:
        Lists may be empty when source ticket lacks detail.
    """

    title: str
    problem: str
    impact: str
    suggested_next_steps: list[str]
    risks: list[str] = []


class ReplyDraft(BaseModel):
    """Represent a customer reply draft.

    Parameters:
        subject: Suggested reply subject.
        body: Reply body text.
        tone: Communication tone.
        requires_human_review: Whether human review is required.

    Returns:
        Validated reply draft.

    Edge cases:
        Human review must remain true for safety in this V1.
    """

    subject: str
    body: str
    tone: str = "professional"
    requires_human_review: bool = True


class UserStory(BaseModel):
    """Represent a ClickUp-oriented user story.

    Parameters:
        title: ClickUp task title.
        description: ClickUp task description.
        acceptance_criteria_in_gerkin: Acceptance criteria in Given/When/Then format.
        constraints: Technical notes and constraints.
        user_story_statement: User story statement.
        out_of_scope: Explicitly excluded work.
        requested_by: Requester information.
        functional_description: Functional behavior description.

    Returns:
        Validated ClickUp-oriented user story.

    Edge cases:
        Empty fields should be avoided by prompt and mock fallback.
    """

    title: str
    description: str
    acceptance_criteria_in_gerkin: str
    constraints: str
    user_story_statement: str
    out_of_scope: str
    requested_by: str
    functional_description: str

    def to_markdown(self) -> str:
        """Convert user story to a readable Markdown description.

        Parameters:
            None.

        Returns:
            Markdown representation using the ClickUp-oriented fields.

        Edge cases:
            Empty sections render as headings with empty content.
        """
        sections = [
            self.description,
            f"User Story Statement:\n{self.user_story_statement}",
            f"Functional Description:\n{self.functional_description}",
            f"Acceptance Criteria:\n{self.acceptance_criteria_in_gerkin}",
            f"Technical Notes / Constraints:\n{self.constraints}",
            f"Out of Scope:\n{self.out_of_scope}",
            f"Requested By:\n{self.requested_by}",
        ]
        return "\n\n".join(sections)


class AiDraftDocument(BaseModel):
    """Represent an AI draft persisted in MongoDB.

    Parameters:
        fresh_ticket_id: Fresh ticket identifier.
        type: Draft type.
        content: Human-readable content.
        structured_content: Validated structured payload.
        model: AI model name.
        prompt_version: Prompt version used.

    Returns:
        Mongo-ready AI draft payload.

    Edge cases:
        structured_content must match the selected type contract.
    """

    fresh_ticket_id: str
    type: DraftType
    content: str
    structured_content: dict[str, Any]
    model: str
    prompt_version: str


class SummaryWorkflowResponse(BaseModel):
    """Represent summary workflow API response.

    Parameters:
        ticket_id: Fresh ticket identifier.
        type: Draft type.
        summary: Structured summary.
        draft_id: Stored AI draft ID.
        workflow_run_id: Workflow run ID.

    Returns:
        Summary result for frontend.

    Edge cases:
        IDs are stringified Mongo ObjectIds.
    """

    ticket_id: str
    type: Literal["summary"]
    summary: TicketSummary
    draft_id: str
    workflow_run_id: str


class DraftReplyWorkflowResponse(BaseModel):
    """Represent draft reply workflow API response.

    Parameters:
        ticket_id: Fresh ticket identifier.
        type: Draft type.
        draft: Structured reply draft.
        draft_id: Stored AI draft ID.
        workflow_run_id: Workflow run ID.

    Returns:
        Draft reply result for frontend.

    Edge cases:
        Reply is never sent automatically.
    """

    ticket_id: str
    type: Literal["reply"]
    draft: ReplyDraft
    draft_id: str
    workflow_run_id: str
